# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/projects

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/projects

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/projects/CMakeFiles /workspaces/projects//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/projects/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named myapp

# Build rule for target.
myapp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 myapp
.PHONY : myapp

# fast build rule for target.
myapp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/build
.PHONY : myapp/fast

BudgetCalculator.o: BudgetCalculator.cpp.o
.PHONY : BudgetCalculator.o

# target to build an object file
BudgetCalculator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/BudgetCalculator.cpp.o
.PHONY : BudgetCalculator.cpp.o

BudgetCalculator.i: BudgetCalculator.cpp.i
.PHONY : BudgetCalculator.i

# target to preprocess a source file
BudgetCalculator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/BudgetCalculator.cpp.i
.PHONY : BudgetCalculator.cpp.i

BudgetCalculator.s: BudgetCalculator.cpp.s
.PHONY : BudgetCalculator.s

# target to generate assembly for a file
BudgetCalculator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/BudgetCalculator.cpp.s
.PHONY : BudgetCalculator.cpp.s

Database.o: Database.cpp.o
.PHONY : Database.o

# target to build an object file
Database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/Database.cpp.o
.PHONY : Database.cpp.o

Database.i: Database.cpp.i
.PHONY : Database.i

# target to preprocess a source file
Database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/Database.cpp.i
.PHONY : Database.cpp.i

Database.s: Database.cpp.s
.PHONY : Database.s

# target to generate assembly for a file
Database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/Database.cpp.s
.PHONY : Database.cpp.s

Equipment.o: Equipment.cpp.o
.PHONY : Equipment.o

# target to build an object file
Equipment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/Equipment.cpp.o
.PHONY : Equipment.cpp.o

Equipment.i: Equipment.cpp.i
.PHONY : Equipment.i

# target to preprocess a source file
Equipment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/Equipment.cpp.i
.PHONY : Equipment.cpp.i

Equipment.s: Equipment.cpp.s
.PHONY : Equipment.s

# target to generate assembly for a file
Equipment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/Equipment.cpp.s
.PHONY : Equipment.cpp.s

Event.o: Event.cpp.o
.PHONY : Event.o

# target to build an object file
Event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/Event.cpp.o
.PHONY : Event.cpp.o

Event.i: Event.cpp.i
.PHONY : Event.i

# target to preprocess a source file
Event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/Event.cpp.i
.PHONY : Event.cpp.i

Event.s: Event.cpp.s
.PHONY : Event.s

# target to generate assembly for a file
Event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/Event.cpp.s
.PHONY : Event.cpp.s

Staff.o: Staff.cpp.o
.PHONY : Staff.o

# target to build an object file
Staff.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/Staff.cpp.o
.PHONY : Staff.cpp.o

Staff.i: Staff.cpp.i
.PHONY : Staff.i

# target to preprocess a source file
Staff.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/Staff.cpp.i
.PHONY : Staff.cpp.i

Staff.s: Staff.cpp.s
.PHONY : Staff.s

# target to generate assembly for a file
Staff.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/Staff.cpp.s
.PHONY : Staff.cpp.s

Vendor.o: Vendor.cpp.o
.PHONY : Vendor.o

# target to build an object file
Vendor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/Vendor.cpp.o
.PHONY : Vendor.cpp.o

Vendor.i: Vendor.cpp.i
.PHONY : Vendor.i

# target to preprocess a source file
Vendor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/Vendor.cpp.i
.PHONY : Vendor.cpp.i

Vendor.s: Vendor.cpp.s
.PHONY : Vendor.s

# target to generate assembly for a file
Vendor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/Vendor.cpp.s
.PHONY : Vendor.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/main.cpp.s
.PHONY : main.cpp.s

venue.o: venue.cpp.o
.PHONY : venue.o

# target to build an object file
venue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/venue.cpp.o
.PHONY : venue.cpp.o

venue.i: venue.cpp.i
.PHONY : venue.i

# target to preprocess a source file
venue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/venue.cpp.i
.PHONY : venue.cpp.i

venue.s: venue.cpp.s
.PHONY : venue.s

# target to generate assembly for a file
venue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/venue.cpp.s
.PHONY : venue.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... myapp"
	@echo "... BudgetCalculator.o"
	@echo "... BudgetCalculator.i"
	@echo "... BudgetCalculator.s"
	@echo "... Database.o"
	@echo "... Database.i"
	@echo "... Database.s"
	@echo "... Equipment.o"
	@echo "... Equipment.i"
	@echo "... Equipment.s"
	@echo "... Event.o"
	@echo "... Event.i"
	@echo "... Event.s"
	@echo "... Staff.o"
	@echo "... Staff.i"
	@echo "... Staff.s"
	@echo "... Vendor.o"
	@echo "... Vendor.i"
	@echo "... Vendor.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... venue.o"
	@echo "... venue.i"
	@echo "... venue.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

